#!/bin/bash

set -e
current_dir=$(pwd)
pushd ../pax/pax-cli
cargo build
popd

# Initialize a flag to check for --release
is_release=false

# Loop through arguments to check for --release
for arg in "$@"; do
    if [ "$arg" = "--release" ]; then
        is_release=true
        break
    fi
done

# Conditionally set PUB_PAX_SERVER based on the --release flag
if [ "$is_release" = true ]; then
    PAX_PUBLISH_BUTTON=1 PAX_WORKSPACE_ROOT=../pax ../pax/target/debug/pax-cli "$@" --path="$current_dir" --libdev
else
    PUB_PAX_SERVER=0.0.0.0:9090 PAX_PUBLISH_BUTTON=1 PAX_WORKSPACE_ROOT=../pax ../pax/target/debug/pax-cli "$@" --path="$current_dir" --libdev
fi
