#!/bin/bash

### Helper script for pax libdev, allowing pax-cli-like ergonomics inside the pax-example directory
###
### For example, from @/pax root:
### `cd pax-example && ./pax run --target=macos`
### `cd pax-example && ./pax parse`
### `cd pax-example && ./pax libdev build-chassis`

set -e
current_dir=$(pwd)
pushd ../pax/pax-cli
cargo build
popd
PUB_PAX_SERVER=http://localhost:9090 PAX_PUBLISH_BUTTON=1 PAX_WORKSPACE_ROOT=../pax ../pax/target/debug/pax-cli "$@" --path="$current_dir" --libdev
#PAX_PUBLISH_BUTTON=1 PAX_WORKSPACE_ROOT=../pax ../target/debug/pax-cli "$@" --path="$current_dir" --libdev
